import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { GlobalNavigationListener } from '@shared/components/progress'
import { ThemeProvider } from '@/shared/provider'

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className={`${nunitoSans.variable}`}>
    <body className='antialiased'>
    <GlobalNavigationListener />
    <ThemeProvider>{children}</ThemeProvider>
    <div id="modal-root"></div>
    </body>
    </html>
  )
}
